### ISSUE TITLE
Error Unicode

### ISSUE THREAD

**Issue by Jostino** [marclave/InstaBot#29]
```
Traceback (most recent call last):
  File "InstaBot.py", line 109, in <module>
    like(br, hashtags)
  File "InstaBot.py", line 53, in like
    response = br.open(WEBSTA_URL +"tag/" + urllib.quote(hashtag.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 0: ordinal not in range(128)
```
Lanunched the bot and after the list of hashtags appear this error above.

**Comment by Jostino** [comment]
Python 2.7
unicode set on ascii instead of utf-8 :cry:
