### ISSUE TITLE
OAuthRateLimitException is thrown after 30 liked images

### ISSUE THREAD

**Issue by fro35i** [marclave/InstaBot#5]
After I liked 30 images, I get the following error message:
{"meta":{"error_type":"OAuthRateLimitException","code":429,"error_message":"The maximum number of requests per hour has been exceeded. You have made 38 requests of the 30 allowed in the last hour."}}

So it seems that only 30 requests are allowed in one hour? Does instagram have such a bad request limitation now or does the limitation of unsigned requests might be the problem?

**Comment by jerryromel** [comment]
Any update, would love to see progress

**Comment by jrefos1** [comment]
Hi, Can you help me?
I'm getting this error after running the script. I also don't know what ip i must use. ipv4 adress or default gateway? I'm new with this. thanks for helping :)

ERROR:

Liking #motivation
Traceback (most recent call last):
  File "InstaBot.py", line 113, in <module>
    like(br, hashtags)
  File "InstaBot.py", line 79, in like
    response = encodeAndRequest(id)
  File "InstaBot.py", line 14, in encodeAndRequest
    signature = hmac.new(str(profile['CREDENTIALS']['CLIENT_SECRET']), profile['
IP'], sha256).hexdigest()
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jrefos1** [comment]
Hi,

Any new updates in this thread? the script stop working after 30 likes :(

**Comment by chinciusan** [comment]
"the script stop working after 30 likes" -same issue for me

**Comment by marclave** [comment]
Hi everyone, I have not been updating this thread because i worked extensively on a fix but found no workaround, I know the 30 like limit is not enjoyable; however, I have been very busy and will try again next weekend. I will update this thread, thank you.
- Marc

**Comment by AyuReadyX** [comment]
you think mechanize would be better for passing the hmac sig etc instead of pycurl? just a guess, i forked btw ill be doing some messing with it

**Comment by ramiyahya** [comment]
Hi Marclave,

Do you have any plans on fixing this issue?

**Comment by marclave** [comment]
@ramiyahya i have tried many approaches and no ideas really..

**Comment by arvand** [comment]
@marclave Can't you edit the code in a way so that the bot will like the pictures and follow users through webstagram?
