### ISSUE TITLE
pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')

### ISSUE THREAD

**Issue by fludkov-valerii** [marclave/InstaBot#8]
Hi marclave!

I have following error after run InstaBot.py:
# 

```
        InstaBot
Developed by Marc Laventure
```
# 

Liking #I
Traceback (most recent call last):
  File "InstaBot.py", line 113, in <module>
    like(br, hashtags)
  File "InstaBot.py", line 79, in like
    response = encodeAndRequest(id)
  File "InstaBot.py", line 22, in encodeAndRequest
    c.perform()
pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')

How can I resolve this?

**Comment by patruff** [comment]
I get this error too!

**Comment by ArtVasykt** [comment]
I solved the problem this way:
1. pip install certifi
2. Open InstaBot.py
2. add "import certifi"
3. before :
`
c.setopt(c.URL, url)
`
add:
       `c.setopt(pycurl.CAINFO, certifi.where())`

P.S sorry for my English

**Comment by peter123023** [comment]
curl.setopt(pycurl.SSL_VERIFYPEER, 0) is key point

**Comment by ashishsingh007** [comment]
I am getting same error when moving my code on Unix server but same works on windows. Don't know what is wrong. 
Tried multiple option such 
Ssl verify option set false

**Comment by rpd-tweet** [comment]
This is because your browser signature is banned by the owner. This is an identity error ( ERROR 1010)
